---
name: Bruno Testaguzza Carlin
position: "Trainee"
address: "Ernst & Young - São Paulo"
phone: +55 11 99376-5775
www: twosidesdata.netlify.com/
email: "brunotestaguzza@gmail.com"
twitter: BrunoTestaguzza
github: brunocarlin
linkedin: bruno-carlin-451007172
date: "`r format(Sys.time(), '%B %Y')`"
output: vitae::awesomecv
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
```

# Education

## Insper

[Post-graduate Degree Data Science and Decisions](https://www.insper.edu.br/pos-graduacao/programas-avancados/programa-avancado-em-data-science-e-decisao/)

2019-2020.

[Graduation Economics](https://www.insper.edu.br/graduacao/economia/)

2014-2018.

## Digital House

[Studying Data Science](https://br.digitalhouse.com/curso/data-science/)

## Porto Seguro

[Foreign Commerce - High School](https://www.portoseguro.org.br/conteudo/detalhe/currculo-brasileiro/ensino-mdio-comrcio-exterior)

2013.

# Experience

## Bayer

Right now I am allocated at a new area of the company called Account Receivable Data Analysis, I will be working on Data Science models and the creation of data procedures.

I worked as a Credit analyst for 3 months, doing  financial analysis of clients and developing some scripts in R to automate daily tasks.

## Driven Consulting

I worked as a Data Scientist Consultant on projects for the BI area, working on problems like the future amount of products on our clients stores.

## Ernst & Young

I worked as a trainee at EY, using my experience working with data and technology, delivering large scale accounting projects that require automation, I am also worked on the documentation and analysis of already implemented solutions.

## Bayer

I have 1 year of working experience as an Intern for the Risk Management, Reporting area in Bayer. I was responsible for the creation, automation and maintenance of several credit and cash flow reports. My most remarkable skill when doing these regular tasks was combining my VBA and Excel knowledge to create and improve Dashboards.

I executed a forecasting project that involved using my own algorithm created in R to improve automatic forecasting performance of time series by ensemble models, I then hierarchical forecasts bringing information on all branches of receivables together, most importantly the project proved the viability of doing automated forecasts, potentially reducing working hours therefore costs.

# Languages

## Portuguese

Native.

## English

Advanced.

No certification, used regularly.


## German

Basic-Intermediary.

B1 Certification

## Spanish

Basic.

No Certification.



# Data Science Skills

I am learning Data Science, following blogs, Reddit, reading books, doing online and on site courses, watching conference videos and more.

I am well versed into using the tidyverse for Data Analysis and Statistical Inference and doing time series forecasts.

## Technologies

R, SQL, Python.