---
name: Bruno Testaguzza Carlin
position: "Trainee"
address: "Ernst & Young - São Paulo"
phone: +55 11 99376-5775
www: twosidesdata.netlify.com/
email: "brunotestaguzza@gmail.com"
twitter: BrunoTestaguzza
github: brunocarlin
linkedin: bruno-carlin-451007172
date: "`r format(Sys.time(), '%B %Y')`"
output: vitae::awesomecv
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
```

# Educação

## Insper

[Pós-graduação Data Science e decisão](https://www.insper.edu.br/pos-graduacao/programas-avancados/programa-avancado-em-data-science-e-decisao/)

2019-2020.

[Bacharelado em Economia](https://www.insper.edu.br/graduacao/economia/)

2014-2018.

## Digital House

[Cursando Data Science](https://br.digitalhouse.com/curso/data-science/)

## Porto Seguro

[Curso Técnico - Comércio Exterior](https://www.portoseguro.org.br/conteudo/detalhe/currculo-brasileiro/ensino-mdio-comrcio-exterior)

Finalizado 2013

# Experiência

## Bayer

Começo esse ano em uma nova área da Empresa chamada, Contas a Receber Análise de Dados, vou trabalhar com modelos de Ciência de dados e criação de procedimentos de dados em toda a América latina.


Trabalhei 3 meses como analista de Crédito, fazendo analises de crédito dos clientes e desenvolvendo scripts para automação de tarefas diárias em R.

## Driven Consulting

Trabalho como Consultor de Ciência de Dados na área de BI resolvendo problemas como o estoque futuro nos clientes.

## [Ernst & Young](https://www.ey.com/br/pt/services/assurance/financial-accounting-advisory-services)

Trabalhei como Trainee resolvendo problemas contábeis em grande escala, também realizei a análise e documentação de sistemas já implementados.

## Bayer

Tenho um ano de experiencia de trabalho como estagiário de finanças da área de Risk Managment na Bayer. Fui responsável pela criação, automação e manutenção de relatórios para a área de crédito e tesouraria. Meu principal diferencial nessas tarefas foi a busca por novas maneiras de melhorar nossos processos, usando ferramentas como o VBA, power query e power pivot.

Executei um projeto de previsões usando o meu próprio algoritmo escrito na linguagem R, a ideia do projeto foi melhorar nossas previsões de forma automática.

# Idiomas

## Inglês

Avançado-Fluente.

Sem certificação porém eu uso no dia a dia, realizei intercâmbio para a inglaterra pelo escola e já viajei para diversos países usando o inglês como meio principal de comunicação.

## Alemão

Básico-Intermediario

Certificação B1, pórem não pratico desde o Colégio.

## Espanhol

Básico

# Interesses profissionais

Ciência de dados, finanças e economia.