---
name: Bruno Testaguzza Carlin
position: "Trainee"
address: "Ernst & Young - São Paulo"
phone: +55 11 99376-5775
www: twosidesdata.netlify.com/
email: "brunotestaguzza@gmail.com"
twitter: BrunoTestaguzza
github: brunocarlin
linkedin: bruno-carlin-451007172
date: "`r format(Sys.time(), '%B %Y')`"
output: vitae::awesomecv
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
```

# Education

## Insper

[Graduation Economics](https://www.insper.edu.br/graduacao/economia/)

2014-2018.

## Digital House

[Studying Data Science](https://br.digitalhouse.com/curso/data-science/)

## Porto Seguro

[Foreign Commerce - High School](https://www.portoseguro.org.br/conteudo/detalhe/currculo-brasileiro/ensino-mdio-comrcio-exterior)

2013.

# Experience

## Bayer

I have 1 year of working experience as an Intern for the Risk Managment, Reporting area in Bayer. I was responsible for the creation, automation and maintance of several credit and cash flow reports. My most remarkble skill when doing these regular tasks was combining my VBA and Excel knowledge to create and improve Dashboards.

I executed a forecasting project that involved using my own algorithm created in R to improve automatic forecasting performance of time series by ensemble models, I then hirarhical forecasts bringing information on all branches of recevables toghether, most importanly the project proved the viability of doing automated forecasts, potencially reducing working hours threfore costs.

## Ernst & Young

Trainee [FAAS](https://www.ey.com/us/en/services/assurance/financial-accounting-advisory-services).

In training.

# Languages

## Portuguese

Native.

## English

Advanced.

No certification, used regularly.


## German

Basic-Intermediary.

B1 Certification

## Spanish

Basic.

No Certification.

## Data Science Skills

I am an  eager to learn Data Science, following blogs, reddit, reading books, doing online an on site courses, watching conference videos and more.

I am well versed into using the tidyverse for Data Analisys and Statistical Inference, with a formal background aquired in optional courses on my college.

I have studied the most about time series.

Advanced R.

Intermediary Python.
